name: Build, Push and Deploy Image to Amazon Elastic Kubernetes Service

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Build and Push Image to Elastic Container Registry
      run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v1c7n0e8
          docker build -t saroproject .
          docker tag saroproject:latest public.ecr.aws/v1c7n0e8/saroproject:latest
          docker push public.ecr.aws/v1c7n0e8/saroproject:latest

    - name: Deploy Image to Elastic Kubernetes Service
      run: |
          aws eks --region us-east-2 update-kubeconfig --name timi-project
          kubectl create deployment project --image=public.ecr.aws/v1c7n0e8/saroproject:latest
          kubectl expose deployment project --type=LoadBalancer --port 80 --target-port 8080

