name: Push to moh

on:
  push:
    branches:
      - main

jobs:
  push_to_another_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Another Repository
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      with:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        SOURCE-DIRECTORY: ./  # Set this to the root of your repository
        DESTINATION-GITHUB-USERNAME: onisa2
        DESTINATION-REPOSITORY-NAME: mohh
        USER-EMAIL: phanthrr.lily@gmail.com
        COMMIT-MESSAGE: 'Pushed from $GITHUB_REF'
        TARGET-BRANCH: main
        EXTRA-ARGS: '--force'  # Add force-push option
