name: workflow_01

on:
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'
    types:
      - Trigger Workflow 

    workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':userName'

        workflow2_repo_github:
         description: 'repo-name'
         required: true
         default: ':repoName'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow 2
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$workflow2_github_account/$workflow2_repo_github"'" }}' \
            "https://api.github.com/repos/$workflow2_github_account/$workflow2_repo_github/dispatches"

      - name: Checkout Repository
        uses: actions/checkout@v3
