name: Trigger Workflow in Target Repo

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'cronjob'
        required: true
        type: string
      branch:
        description: 'Main'
        required: true
        type: string

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Target Repo
        uses: actions/checkout@v2
      - name: Dispatch workflow in Target Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.event.inputs.repository }}
          event-type: 'workflow_dispatch'
          client-payload: '{"branch": "${{ github.event.inputs.branch }}"}'

jobs2:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
