name: Trigger Workflow in Target Repo

on:
  workflow_dispatch:
    inputs:
      repository: cronjob
        description: 'cronjob'
        required: true
        type: string
      branch:
        description: 'Main'
        required: true
        type: string

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Target Repo
        uses: actions/checkout@v2
      - name: Dispatch workflow in Target Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.event.inputs.repository }}
          event-type: 'workflow_dispatch'
          client-payload: '{"branch": "${{ github.event.inputs.branch }}"}'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs2:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
