name: Update Image Tag

on:
  push:
    branches:
      - main

jobs:
  update_image_tags:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update Image Tag
      run: |
        # Implement your logic to update the image tag in your staging environment
        # This could involve modifying configuration files or scripts

    - name: Check for Changes
      run: |
        BEFORE_COMMIT=$(git rev-parse ${{ github.event.before }})
        CURRENT_COMMIT=$(git rev-parse HEAD)

        if [ "$BEFORE_COMMIT" != "$CURRENT_COMMIT" ]; then
          echo "Changes detected. Proceeding with commit and push."
        else
          echo "No changes to commit. Exiting..."
          exit 0
        fi

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag"
        git remote add cronjob-repo https://github.com/Onisa2/cronjob.git  # Replace with the actual URL of your cronjob repository
        git push cronjob-repo main
