name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Working Directory
        run: cd $GITHUB_WORKSPACE

      - name: Check if build output exists
        run: |
          if [ -d "cloudrun" ]; then
            echo "Build output already exists. Skipping build."
          else
            echo "Build output does not exist. Running build script."
            sh ./build.sh
          fi

      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'cloudrun'
          destination-github-username: 'onisa2'
          destination-repository-name: 'mohh'
          user-email: Phanthrr.lily@gmail.com
          target-branch: main
