name: Update Image Tag

on:
  push:
    branches:
      - main

jobs:
  update_image_tags:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Update Image Tag
      run: |
        # Implement your logic to update the image tag in your staging environment
        # This could involve modifying configuration files or scripts

    - name: Check for Changes
      run: |
        git diff --exit-code || { echo "No changes to commit. Exiting..."; exit 0; }

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag"
        git remote add cronjob-repo https://github.com/Onisa2/moh.git  # Replace with the actual URL of your cronjob repository
        git push moh-repo main
