name: Update Image Tag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_image_tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Image Tag
      run: |
        # Implement your logic to update the image tag in your staging environment
        # This could involve modifying configuration files or scripts

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag"
        git push origin main
