name: Trigger Workflow_02

on:
  workflow_dispatch:
    inputs:
      target_repo_owner:
        description: 'GitHub Account Owner of Target Repo'
        required: true
        default: 'Onisa2'  # Replace with the GitHub username of the target repository
      target_repo_name:
        description: 'Name of Target Repo'
        required: true
        default: 'cronjob'  # Replace with the name of the target repository

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -u ${{ secrets.TOKEN }} \
            -d '{"event_type": "update-image-tags", "client_payload": { "sha": "'"$GITHUB_SHA"'" }}' \
            "https://api.github.com/repos/${{ github.event.inputs.target_repo_owner }}/${{ github.event.inputs.target_repo_name }}/dispatches"
